services:
  - type: web
    name: photographer-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: PhotographerApp
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:enZLdQt0w5JG//JiwYyFoDiEaIcCQc0SPHWebOl8Mos=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: info

      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1pnsoruibrs73duri00-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: photographdb
      - key: DB_USERNAME
        value: photographerdb_user
      - key: DB_PASSWORD
        sync: false

      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120

      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: gomezkyle3102@gmail.com
      - key: MAIL_PASSWORD
        value: nningjrzfcfmgnmg
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: gomezkyle3102@gmail.com
      - key: MAIL_FROM_NAME
        value: "PhotographerApp"

      - key: HASH_SECRET
        value: XxUdCwmw9kx300Hpsrsse3DywB6uQI0K
